#!/bin/bash

# theming
export GUM_INPUT_CURSOR_FOREGROUND=$PEACH

if [ $# -gt 0 ]; then
  STAGE=$1
else
  # if the user did not provide an environment
  STAGE=$(gum choose "Acceptance" "Testing" "Production")
fi

if [[ $STAGE = "Production" ]]; then
  API=$API_PROD
elif [[ $STAGE = "Testing" ]]; then
  API=$API_TEST
elif [[ $STAGE = "Acceptance" ]]; then
  API=$API_ACC
else
  echo "Invalid stage provided"
  exit 1
fi

export ACCESS_TOKEN="$(az account get-access-token --resource $API | jq -r '.accessToken')"

